title = "Conxian Gateway gitleaks configuration"

[extend]
useDefault = true

[allowlist]
description = "Allowlist false positives or known examples in history"
commits = [
  "58ea2ffc728cf8433dab28c9ba35414e4343c92b"
]
regexes = [
  '''(?i)public_key.{0,64}0[23][0-9a-f]{64}''',
  '''0[23][0-9a-f]{64}''',
]
fingerprints = [
  "58ea2ffc728cf8433dab28c9ba35414e4343c92b:README.md:sidekiq-secret:42",
  "58ea2ffc728cf8433dab28c9ba35414e4343c92b:README.md:aws-access-token:221",
  "58ea2ffc728cf8433dab28c9ba35414e4343c92b:README.md:aws-access-token:223",
  "58ea2ffc728cf8433dab28c9ba35414e4343c92b:README.md:aws-access-token:259",
]
