[package]
name = "conxian-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
hex = "0.4.3"
rusqlite = { workspace = true }
aes-gcm = { workspace = true }
async-trait = { workspace = true }
