[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
conxian-core.workspace = true
bitcoin.workspace = true
bitcoincore-rpc.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
minreq = { version = "3.0.0", features = ["https", "json-using-serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
reqwest = { version = "0.13", features = ["json"] }
rgb-core = { version = "0.12", optional = true, features = ["bitcoin", "serde"] }
rgb-std = { version = "0.12.0-rc.3", optional = true }
bp-esplora = { version = "0.12.0-rc.3", optional = true, default-features = false, features = ["blocking-https-rustls"] }

[features]
rgb-native = ["rgb-core", "rgb-std", "bp-esplora"]
