[package]
name = "compliance"
version.workspace = true
edition.workspace = true

[dependencies]
conxian-core.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
bitcoin = { workspace = true }
hex = "0.4.3"
rand = "0.8"
chrono = { workspace = true }
serde_json = { workspace = true }
uuid = { version = "1.7.0", features = ["v4"] }
tokio = { workspace = true, features = ["full"] }
quick-xml = "0.38.1"
hmac = "0.12.1"
sha2 = "0.10.8"
