[package]
name = "compliance"
version.workspace = true
edition.workspace = true

[features]
mock-integrations = []

[dependencies]
conxian-core.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
bitcoin = { workspace = true }
hex = "0.4.3"
rand = "0.8"
chrono = { workspace = true }
serde_json = { workspace = true }
serde_jcs = "0.2.0"
uuid = { version = "1.7.0", features = ["v4"] }
tokio = { workspace = true, features = ["full"] }
quick-xml = "0.38.1"
hmac = "0.12.1"
sha2 = "0.10.8"
risc0-zkvm = { version = "5.0.0-rc.1", default-features = false, features = ["std"] }
base64 = "0.22.1"
borsh = "1.5.5"
memchr = "2.8.0"
bytemuck = "1.21.0"
bincode = "1.3.3"
