name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: Conxian/.github/.github/workflows/dependency-review.yml@f2d658c734b41b96d999086f68c34f828a2a89c9 # main
