name: Secret Scan

on:
  pull_request:
    branches: [ main, staged, dev ]
  push:
    branches: [ main, staged, dev ]

permissions:
  contents: read

jobs:
  gitleaks:
    name: Secret Scan (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@f693587520e54cd01ebcdcfb758b291d29528f41 # v2.3.7
